import pyvista as pv
import networkx as nx
import numpy as np
import os
import sys
import re

# Metadata
__author__ = "HSINI MOHAMED"
__project__ = "Entity Saliency & Relationship Mapper"

class SaliencyMapper:
    def __init__(self):
        self.G = nx.Graph()
        self.original_text = ""

    def process_text(self, text):
        self.original_text = text
        self.G.clear()
        
        # Enhanced Entity Extraction Heuristic
        # Captures capitalized sequences as entities
        sentences = re.split(r'[.!?]', text)
        for sent in sentences:
            # Find capitalized words (excluding start of sentence if it's common)
            words = sent.split()
            sent_entities = []
            current_ent = []
            
            for i, w in enumerate(words):
                clean_w = w.strip(",.?!()\"")
                if clean_w and clean_w[0].isupper() and len(clean_w) > 1:
                    current_ent.append(clean_w)
                else:
                    if current_ent:
                        ent_name = " ".join(current_ent)
                        sent_entities.append(ent_name)
                        current_ent = []
            if current_ent:
                ent_name = " ".join(current_ent)
                sent_entities.append(ent_name)
            
            for ent in sent_entities:
                if ent not in self.G:
                    self.G.add_node(ent)
                    
            for i in range(len(sent_entities)):
                for j in range(i + 1, len(sent_entities)):
                    self.G.add_edge(sent_entities[i], sent_entities[j])
        
        self.update_saliency()

    def update_saliency(self):
        if not self.G.nodes: return
        try:
            # Use PageRank for Saliency
            scores = nx.pagerank(self.G, weight=None)
            for node, score in scores.items():
                self.G.nodes[node]['saliency'] = score
        except:
            # Fallback for small/disconnected graphs
            for node in self.G.nodes:
                self.G.nodes[node]['saliency'] = 1.0 / len(self.G.nodes)

    def remove_entity(self, name):
        if name in self.G:
            self.G.remove_node(name)
            self.update_saliency()
            return True
        return False

    def generate_wiki_article(self):
        if not self.G.nodes:
            return "No semantic data available."
            
        sorted_entities = sorted(self.G.nodes(data=True), key=lambda x: x[1].get('saliency', 0), reverse=True)
        top_ent = sorted_entities[0][0]
        
        wiki = f"""# SEMANTIC AUTHORITY REPORT: {top_ent.upper()}
Generated by {__project__} Neural Engine
Author: {__author__}

## 1. Entity Saliency Overview
In the current Knowledge Graph, **{top_ent}** emerges as the primary semantic anchor with a Saliency Score of **{sorted_entities[0][1].get('saliency', 0):.4f}**. 
This indicates that {top_ent} is highly interconnected and likely prioritized by LLM RAG systems.

## 2. Relational Knowledge Graph
The neural proximity of the following entities suggests a strong brand association:
"""
        neighbors = list(self.G.neighbors(top_ent))
        for n in neighbors:
            wiki += f"- {n}: Active Relationship Node\n"
            
        wiki += "\n## 3. Brand Resilience Metrics\n"
        wiki += f"- Network Density: {nx.density(self.G):.4f}\n"
        wiki += f"- Connected Components: {nx.number_connected_components(self.G)}\n"
        wiki += f"- Semantic Core: {top_ent}\n"
        
        return wiki

class NeuralGraphVisualizer:
    def __init__(self, mapper):
        self.mapper = mapper
        self.plotter = pv.Plotter(title=__project__)
        self.plotter.set_background("#000210")
        self.pos = {}
        self.node_actors = {}
        
    def render_graph(self):
        self.plotter.clear()
        G = self.mapper.G
        if not G.nodes: return
        
        # 3D Spatial Layout
        self.pos = nx.spring_layout(G, dim=3, seed=42)
        
        # Enhanced Pattern-Based Categorization (Scalable for 100+ entities)
        def get_color(node):
            node_l = node.lower()
            # People: Names with Titles or specific common names
            if any(p in node_l for p in ["sam ", "greg ", "jensen ", "ceo", "cto", "founder", "vp", "executive", "director"]):
                return "#FFD700" # GOLD
            # Companies: Corporate suffixes or known tech giants
            if any(c in node_l for c in ["inc", "corp", "systems", "labs", "tech", "ai", "ltd", "google", "meta", "apple", "amazon", "microsoft", "nvidia", "openai", "anthropic", "xai", "groq", "mistral", "intel", "amd", "tsmc"]):
                return "#00FF7F" # SPRING GREEN
            # Tech/Models: Model names or technology terms
            if any(t in node_l for t in ["gpt", "llama", "gemini", "claude", "model", "neural", "gpu", "chip", "cuda", "transformer", "h100", "a100", "b200"]):
                return "#00BFFF" # DEEP SKY BLUE
            return "#E0E0E0" # PLATINUM for General Entities
        
        # Render Edges (Neural Pathways)
        for u, v in G.edges:
            start = np.array(self.pos[u])
            end = np.array(self.pos[v])
            line = pv.Line(start, end)
            self.plotter.add_mesh(line, color="#00e5ff", opacity=0.15, line_width=1, pickable=False)
            
        # Render Nodes (Neural Anchors)
        sorted_nodes = sorted(G.nodes(data=True), key=lambda x: x[1].get('saliency', 0), reverse=True)
        leaderboard = "TOP SEMANTIC ANCHORS:\n"
        
        for i, (node, data) in enumerate(sorted_nodes):
            coord = self.pos[node]
            saliency = data.get('saliency', 0.1)
            
            # Leaderboard text (top 5)
            if i < 5:
                leaderboard += f"{i+1}. {node} ({saliency:.3f})\n"
            
            # Size proportional to saliency (Exponential scale for Pro look)
            radius = 0.05 + (saliency ** 0.5) * 0.4
            sphere = pv.Sphere(radius=radius, center=coord)
            
            node_color = get_color(node)
            actor = self.plotter.add_mesh(sphere, color=node_color, smooth_shading=True, name=node, 
                                        pickable=True, ambient=0.3, specular=0.8)
            self.node_actors[node] = actor
            
            # Glowing Labels with Category Colors
            self.plotter.add_point_labels([coord], [node], font_size=11, text_color=node_color, 
                                        always_visible=True, name=f"label_{node}", shadow=True)

        # Pro UI Dashboard (Refined Positioning to avoid overlap)
        self.plotter.add_text(f"NEURAL ENTITY MAP v2.1 - {__author__}", position='upper_left', font_size=11, color='#00e5ff', name="header")
        
        # Category Legend (Pro Look)
        legend = "ENTITY CATEGORIES:\n"
        legend += "● PEOPLE (GOLD)\n"
        legend += "● CORPORATE (GREEN)\n"
        legend += "● TECH/MODELS (CYAN)\n"
        legend += "● GENERAL (PLATINUM)"
        self.plotter.add_text(legend, position=(20, 100), font_size=9, color='white', name="legend")
        
        self.plotter.add_text(leaderboard, position='upper_right', font_size=10, color='#00FF7F', name="leaderboard")
        
        self.plotter.add_text("SYSTEM COMMANDS:\n[L-CLICK] SIMULATE COLLAPSE  [R-CLICK] CAMERA  [SCROLL] ZOOM", 
                              position='lower_left', font_size=8, color='#00e5ff', name="commands")

    def on_node_click(self, mesh):
        if not mesh: return
        # Find which node was clicked
        for node, actor in self.node_actors.items():
            if actor.mapper.dataset == mesh:
                print(f"Removing node: {node} - Simulating Semantic Collapse...")
                self.mapper.G.remove_node(node)
                self.mapper.update_saliency()
                self.render_graph()
                # Update Wiki Article
                with open("authority_article_collapsed.txt", "w") as f:
                    f.write(self.mapper.generate_wiki_article())
                return

    def run(self):
        self.render_graph()
        self.plotter.enable_mesh_picking(callback=self.on_node_click, show=False, left_clicking=True)
        
        # Pro Feature: Cinematic Auto-Orbit & Neural Pulse
        print("Starting Neural Vision Cinema Mode...")
        self.plotter.show(interactive_update=True)
        
        import time
        try:
            t = 0
            while True:
                t += 0.05
                # Cinematic Orbit
                self.plotter.camera.azimuth += 0.15 
                
                # Neural Pulse Animation (Nodes breathe)
                pulse_scale = 1.0 + 0.05 * np.sin(t)
                for node, actor in self.node_actors.items():
                    actor.SetScale(pulse_scale, pulse_scale, pulse_scale)
                
                self.plotter.update()
                time.sleep(0.01)
        except:
            pass # Handle window close

if __name__ == "__main__":
    mapper = SaliencyMapper()
    
    # Massive Tech Ecosystem Corpus (100+ Potential Entities)
    sample_corpus = """
    In the evolving AI landscape, Microsoft Corp and OpenAI remain central partners, 
    while Google DeepMind and Meta AI accelerate their Llama and Gemini deployments. 
    NVIDIA's Jensen Huang and Apple's Tim Cook are pivoting towards on-device AI. 
    Amazon Web Services and Oracle are building massive training clusters with NVIDIA H100 and AMD Instinct chips.
    
    Startups like Anthropic, Mistral AI, and xAI (Elon Musk) are challenging the status quo. 
    The semiconductor war involves TSMC, Intel, and Samsung, all racing for 2nm nodes. 
    Venture capital firms like Andreessen Horowitz and Sequoia Capital are pouring billions into AI Labs.
    
    Key technical breakthroughs in Transformers, MoE (Mixture of Experts), and Quantization 
    are being driven by researchers at Stanford, MIT, and Carnegie Mellon. 
    In the enterprise space, Salesforce, Adobe, and ServiceNow are integrating Agentic AI.
    
    Meanwhile, Groq and Cerebras are developing specialized AI hardware to compete with CUDA. 
    The global AI supply chain includes ASML, Foxconn, and Broadcom, forming a complex neural web.
    """
    
    mapper.process_text(sample_corpus)
    
    # Generate Initial Article
    with open("authority_article.txt", "w") as f:
        f.write(mapper.generate_wiki_article())
        
    print("Graph Data Initialized.")
    print("Initial Wiki Article generated in 'authority_article.txt'.")
    
    app = NeuralGraphVisualizer(mapper)
    app.run()
